### ISSUE TITLE
整个包大小超过 127字节, MQTT 服务器会报错

### ISSUE THREAD

**Issue by raiscui** [yangboz/as3MQTT#12]
我试了 两种 MQTT服务器 都会报错,  超过127位的话 长度计算貌似有错,但是我查了下 好像可变长度这块的代码没有问题,  服务器上接受包的长度的问题是打印出来  topic的 长度 变得巨大, 貌似是 低位的值变道了高位.

**Comment by raiscui** [comment]
报错 掉线

**Comment by yangboz** [comment]
related to #13

**Comment by noson123** [comment]
此问题有解么？ 
正在技术调研中，感谢关注此项目在如今

**Comment by yangboz** [comment]
The minimum size of the packet length field is 1 byte which is for messages with a total length less than 127 bytes.(not including control and length fields).
